### ISSUE TITLE
Generate signature from PKCS#8 (itunes)

### ISSUE THREAD

**Issue by mpoiriert** [sop/pkcs8#1]
Someone suggest me to try your library to do this:

https://developer.apple.com/documentation/storekit/in-app_purchase/generating_a_signature_for_subscription_offers

I just have a .p8 file. Do you think it's possible with your library and how should I proceed ?

Thanks !

**Comment by sop** [comment]
This particular library is just to read encrypted private keys. However i've got other tools to suit your purpose.
I'm not familiar with the signature process you linked, but quickly skimming through here's something to get you going.

```
<?php

use Sop\CryptoBridge\Crypto;
use Sop\CryptoEncoding\PEM;
use Sop\CryptoTypes\AlgorithmIdentifier\Hash\SHA256AlgorithmIdentifier;
use Sop\CryptoTypes\AlgorithmIdentifier\Signature\SignatureAlgorithmIdentifierFactory;
use Sop\CryptoTypes\Asymmetric\PrivateKeyInfo;

require __DIR__.'/vendor/autoload.php';

$private_key_pem = <<<'PEM'
-----BEGIN PRIVATE KEY-----
...<your private key>
-----END PRIVATE KEY-----
PEM;

// load private key
$private_key_info = PrivateKeyInfo::fromPEM(PEM::fromString($private_key_pem));
// combine the parameters
$appBundleId = '';
$keyIdentifier = '';
$productIdentifier = '';
$offerIdentifier = '';
$applicationUsername = '';
$nonce = '';
$timestamp = '';
$data = $appBundleId.'\u2063'.$keyIdentifier.'\u2063'.
    $productIdentifier.'\u2063'.$offerIdentifier.'\u2063'.
    $applicationUsername.'\u2063'.$nonce.'\u2063'.$timestamp;
// signature algorithm
$algo = SignatureAlgorithmIdentifierFactory::algoForAsymmetricCrypto(
    $private_key_info->algorithmIdentifier(),
    new SHA256AlgorithmIdentifier()
);
// generate signature
$signature = Crypto::getDefault()->sign($data, $private_key_info, $algo);
// encode as base64 encoded DER
$encoded_signature = base64_encode($signature->toDER());
echo "${encoded_signature}\n";
// verify signature
$valid = Crypto::getDefault()->verify(
    $data,
    $signature,
    $private_key_info->publicKeyInfo(),
    $algo
);
```

Initialize using `composer require sop/crypto-bridge`.

If your private key is encrypted, then add `sop/pkcs8` add use `EncryptedPrivateKeyInfo::decryptWithPassword()` to retrieve decrypted PrivateKeyInfo.

**Comment by mpoiriert** [comment]
I did try and I still have a error on the other side of the flow (Itunes).

I have a .p8 file that I did convert into a .pem file (using openssl in command line). Could that be the reason it failed ? Is there a way to work with the .p8 file directly ?

My level in encryption is low so any obvious thing that you might think will probably be not obvious for me.

**Comment by sop** [comment]
Open your .p8 file in a text editor and check the contents. Does the file begin with a `-----BEGIN PRIVATE KEY-----` line or similar?
Anyway, if you get a signature string, the key should at least work. The process would throw an exception at some point if there's error with the key.
Also note that by the specification you linked you must pass the **same** nonce (UUID) and timestamp (Unix time) that were used in the signature payload.

**Comment by yaronius** [comment]
@sop many thanks, I had problems with iTunes offers, found this issue and did (almost) exactly as written above. One remark though: as a delimiter you have to use [PHP Unicode codepoint](https://www.php.net/manual/en/migration70.new-features.php#migration70.new-features.unicode-codepoint-escape-syntax), e.g. `"\u{u2063}"`. Also, keep in mind that `$nonce` is lowercase, `$timestamp` is in milliseconds (i.e. `time() * 1000`). And everything will work like a charm!

**Comment by mpoiriert** [comment]
@yaronius  Can you provide me your exact code ? I am still not making it work (I do think I have 2 issues or one is on the client side...) Here is a stackoverflow post (from someone else) that need help too, you'll see my comment.

https://stackoverflow.com/questions/55414749/generating-a-signature-for-subscription-offers-xcode-swift/55733695#55733695

We will be able to close the current issue and bring the conversation there if you want to help !

**Comment by yaronius** [comment]
@mpoiriert as I said, I did mostly as posted above:
```
use Sop\CryptoBridge\Crypto;
use Sop\CryptoEncoding\PEM;
use Sop\CryptoTypes\AlgorithmIdentifier\Hash\SHA256AlgorithmIdentifier;
use Sop\CryptoTypes\AlgorithmIdentifier\Signature\SignatureAlgorithmIdentifierFactory;
use Sop\CryptoTypes\Asymmetric\PrivateKeyInfo;

$private_key_pem = <<<'PEM'
-----BEGIN PRIVATE KEY-----
...
-----END PRIVATE KEY-----
PEM;

// load private key
$private_key_info = PrivateKeyInfo::fromPEM(PEM::fromString($private_key_pem));

// combine the parameters
$appBundleId = 'com.github.yaronius';
$keyIdentifier = 'A1B2C3D4E5';
$productIdentifier = 'product_identifier';
$offerIdentifier = 'offer_identifier';
$applicationUsername = 'username';
$nonce = 'db6ba7a6-9ec2-4504-bcb9-c0dfbdc3d051';
$timestamp = time() * 1000;

$dataArray = [
    $appBundleId,
    $keyIdentifier,
    $productIdentifier,
    $offerIdentifier,
    $applicationUsername,
    $nonce,
    $timestamp
];
$data = implode("\u{2063}", $dataArray);

// signature algorithm
$algo = SignatureAlgorithmIdentifierFactory::algoForAsymmetricCrypto(
    $private_key_info->algorithmIdentifier(),
    new SHA256AlgorithmIdentifier()
);
// generate signature
$signature = Crypto::getDefault()->sign($data, $private_key_info, $algo);

// encode as base64 encoded DER
$encoded_signature = base64_encode($signature->toDER());
```

**Comment by mpoiriert** [comment]
@yaronius 

Did you make the full flow work until the transaction worked on the client side ?

**Comment by yaronius** [comment]
@mpoiriert yes. I found [your issue on Apple forum](https://forums.developer.apple.com/thread/115748). I had exactly the same client error with code 12 and the cryptic message "no iTunes connection". It is actually fixed by a proper signature. In my case, it was fixed by using Sop library.

**Comment by mpoiriert** [comment]
@yaronius We end up finding a issue related to the fact that the frontend developper was logged in with 2 different account (sandbox and it's regular one). Transaction does pass but not when applying a promotion :/ He disconnect from is regular account and just use the sandbox and it worked...

**Comment by marcellofiore** [comment]
Hi, i'm trying to follow your advice... I try to install libraries via composer:

composer.json =>
```
{
    "require": {
        "ramsey/uuid": "^3.8"
    }
}
```
then I try to include the library => composer require sop/crypto-bridge, and I have this error


```
Using version ^0.2.0 for sop/crypto-bridge
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - sop/crypto-types 0.2.1 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - sop/crypto-types 0.2.0 requires ext-gmp * -> the requested PHP extension gmp is missing from your system.
    - sop/crypto-bridge 0.2.0 requires sop/crypto-types ^0.2.0 -> satisfiable by sop/crypto-types[0.2.0, 0.2.1].
    - Installation request for sop/crypto-bridge ^0.2.0 -> satisfiable by sop/crypto-bridge[0.2.0].


Installation failed, reverting ./composer.json to its original content.
```
I'm not very good at this, I hope someone can help me.

**Comment by sop** [comment]
Hi!

Your PHP installation is missing [gmp](https://www.php.net/manual/en/book.gmp.php) extension. If you installed PHP via your OS's package manager, there should be a separate php-gmp package you have to install.

**Comment by mpoiriert** [comment]
After playing around I can confirm the simplest version of for generating a promotion offer signature would be using openssl:

https://stackoverflow.com/questions/55414749/generating-a-signature-for-subscription-offers-xcode-swift/55733695#55733695
